# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/barclays.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &Bank1
        Name: Bank1MSP
        ID: Bank1MSP
        MSPDir: crypto-config/peerOrganizations/bank1.barclays.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Bank1MSP.admin', 'Bank1MSP.peer', 'Bank1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Bank1MSP.admin', 'Bank1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Bank1MSP.admin')"
        AnchorPeers:
            - Host: peer0.bank1.barclays.com
              Port: 7051

    - &Bank2
        Name: Bank2MSP
        ID: Bank2MSP
        MSPDir: crypto-config/peerOrganizations/bank2.barclays.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Bank2MSP.admin', 'Bank2MSP.peer', 'Bank2MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Bank2MSP.admin', 'Bank2MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Bank2MSP.admin')"
        AnchorPeers:
            - Host: peer0.bank1.barclays.com
              Port: 7051

    - &Nonbank
        Name: NonbankMSP
        ID: NonbankMSP
        MSPDir: crypto-config/peerOrganizations/nonbank.barclays.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('NonbankMSP.admin', 'NonbankMSP.peer', 'NonbankMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('NonbankMSP.admin', 'NonbankMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('NonbankMSP.admin')" 
        AnchorPeers:
            - Host: peer0.nonbank.barclays.com
              Port: 7051

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.barclays.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092

    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    OrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Bank1
                    - *Bank2
                    - *Nonbank
    Channelbank:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Bank1
                - *Bank2
            Capabilities:
                <<: *ApplicationCapabilities
    Channelcbdc:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Bank1
                - *Bank2
                - *Nonbank
            Capabilities:
                <<: *ApplicationCapabilities
