OrdererOrgs:
  - Name: Orderer
    Domain: barclays.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Bank1
    Domain: bank1.barclays.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Bank2
    Domain: bank2.barclays.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Nonbank
    Domain: nonbank.barclays.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
