# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.barclays.com:
  peer0.bank1.barclays.com:
  peer0.bank2.barclays.com:
  peer0.nonbank.barclays.com:

networks:
  byfn:

services:

  orderer.barclays.com:
    container_name: orderer.barclays.com
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.barclays.com
    networks:
      - byfn

  peer0.bank1.barclays.com:
    container_name: peer0.bank1.barclays.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.bank1.barclays.com
    networks:
      - byfn

  peer0.bank2.barclays.com:
    container_name: peer0.bank2.barclays.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.bank2.barclays.com
    networks:
      - byfn

  peer0.nonbank.barclays.com:
    container_name: peer0.nonbank.barclays.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.nonbank.barclays.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.bank1.barclays.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bank1.barclays.com/peers/peer0.bank1.barclays.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bank1.barclays.com/peers/peer0.bank1.barclays.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bank1.barclays.com/peers/peer0.bank1.barclays.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bank1.barclays.com/users/Admin@bank1.barclays.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.barclays.com
      - peer0.bank1.barclays.com
      - peer0.bank2.barclays.com
      - peer0.nonbank.barclays.com
    networks:
      - byfn
