# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.barclays.com:
    container_name: orderer.barclays.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/barclays.com/orderers/orderer.barclays.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/barclays.com/orderers/orderer.barclays.com/tls/:/var/hyperledger/orderer/tls
        - orderer.barclays.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.bank1.barclays.com:
    container_name: peer0.bank1.barclays.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.bank1.barclays.com
      - CORE_PEER_ADDRESS=peer0.bank1.barclays.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.bank1.barclays.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bank2.barclays.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bank1.barclays.com:7051
      - CORE_PEER_LOCALMSPID=Bank1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/bank1.barclays.com/peers/peer0.bank1.barclays.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/bank1.barclays.com/peers/peer0.bank1.barclays.com/tls:/etc/hyperledger/fabric/tls
        - peer0.bank1.barclays.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer0.bank2.barclays.com:
    container_name: peer0.bank2.barclays.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.bank2.barclays.com
      - CORE_PEER_ADDRESS=peer0.bank2.barclays.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.bank2.barclays.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bank2.barclays.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bank1.barclays.com:7051
      - CORE_PEER_LOCALMSPID=Bank2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/bank2.barclays.com/peers/peer0.bank2.barclays.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/bank2.barclays.com/peers/peer0.bank2.barclays.com/tls:/etc/hyperledger/fabric/tls
        - peer0.bank2.barclays.com:/var/hyperledger/production
    ports:
      - 9051:7051

  peer0.nonbank.barclays.com:
    container_name: peer0.nonbank.barclays.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.nonbank.barclays.com
      - CORE_PEER_ADDRESS=peer0.nonbank.barclays.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.nonbank.barclays.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.nonbank.barclays.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bank1.barclays.com:7051
      - CORE_PEER_LOCALMSPID=NonbankMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/nonbank.barclays.com/peers/peer0.nonbank.barclays.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/nonbank.barclays.com/peers/peer0.nonbank.barclays.com/tls:/etc/hyperledger/fabric/tls
        - peer0.nonbank.barclays.com:/var/hyperledger/production
    ports:
      - 11051:7051
